version: '3.9'

networks:
  bridge:
    driver: bridge

services:
  wrapper:
    build: .
    networks:
      - bridge
    ports:
      - "8083:80"
    restart: unless-stopped
    volumes:
      - ./downloads:/downloads
      - ./metube-php-servicewrapper:/var/www/html
